ALTER TABLE `site_admin_grade`
	CHANGE COLUMN `grade_id` `grade_id` INT(11) NOT NULL COMMENT '관리자 레벨' AFTER `index_no`,
	CHANGE COLUMN `grade_name` `grade_name` VARCHAR(30) NOT NULL COMMENT '관리자 등급명' AFTER `grade_id`;


ALTER TABLE `site_admin_priv`
	CHANGE COLUMN `grade_id` `grade_id` INT(10) UNSIGNED NOT NULL COMMENT '관리자레벨' AFTER `index_no`,
	CHANGE COLUMN `menu_name` `menu_name` VARCHAR(100) NOT NULL COMMENT '메뉴이름' AFTER `grade_id`,
	CHANGE COLUMN `dir` `dir` VARCHAR(50) NOT NULL COMMENT '경로' AFTER `menu_name`,
	CHANGE COLUMN `code` `code` VARCHAR(50) NOT NULL COMMENT '메뉴코드' AFTER `dir`,
	CHANGE COLUMN `tp` `tp` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `code`;

ALTER TABLE `site_area`
	CHANGE COLUMN `ac_msg` `ac_msg` VARCHAR(50) NOT NULL COMMENT '(고객안내 메세지)' AFTER `ac_alias`,
	CHANGE COLUMN `isuse` `isuse` CHAR(1) NOT NULL COMMENT '사용여부' AFTER `ac_msg`,
	CHANGE COLUMN `orders` `orders` INT(10) UNSIGNED NOT NULL COMMENT '지역순서' AFTER `isuse`;

ALTER TABLE `site_bill`
	CHANGE COLUMN `sdate` `sdate` DATE NOT NULL COMMENT '정산기간(시작)' AFTER `index_no`,
	CHANGE COLUMN `edate` `edate` DATE NOT NULL COMMENT '정산기간(끝)' AFTER `sdate`,
	CHANGE COLUMN `wdate` `wdate` DATETIME NOT NULL COMMENT '작성일' AFTER `edate`,
	CHANGE COLUMN `okdate` `okdate` DATETIME NOT NULL COMMENT '확정일' AFTER `wdate`,
	CHANGE COLUMN `ac1` `ac1` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `okdate`,
	CHANGE COLUMN `ac2` `ac2` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `ac1`,
	CHANGE COLUMN `goac` `goac` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `ac2`;

ALTER TABLE `site_bill_ele`
	CHANGE COLUMN `bill_idx` `bill_idx` INT(10) UNSIGNED NOT NULL COMMENT 'site_bill.index_no' AFTER `index_no`,
	CHANGE COLUMN `com_idx` `com_idx` INT(10) UNSIGNED NOT NULL COMMENT 'site_rentshop.index_no' AFTER `bill_idx`,
	CHANGE COLUMN `account1` `account1` INT(10) NOT NULL COMMENT '단기총액' AFTER `com_idx`,
	CHANGE COLUMN `account2` `account2` INT(10) NOT NULL COMMENT '장기총액' AFTER `account1`,
	CHANGE COLUMN `totalaccount` `totalaccount` INT(10) NOT NULL COMMENT '합계' AFTER `account2`,
	CHANGE COLUMN `goaccount` `goaccount` INT(10) NOT NULL COMMENT '송금총액' AFTER `totalaccount`,
	CHANGE COLUMN `per` `per` TINYINT(3) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `goaccount`,
	CHANGE COLUMN `isok` `isok` CHAR(1) NOT NULL COMMENT '정산 확정체크(Y: 확정)' AFTER `per`,
	CHANGE COLUMN `isgo` `isgo` CHAR(1) NOT NULL COMMENT '지급 여부(Y: 완료)' AFTER `isok`,
	CHANGE COLUMN `godate` `godate` DATETIME NOT NULL COMMENT '지급 일자' AFTER `isgo`,
	CHANGE COLUMN `goname` `goname` VARCHAR(30) NOT NULL COMMENT '지급한 사람' AFTER `godate`;

ALTER TABLE `site_board`
	CHANGE COLUMN `boardid` `boardid` VARCHAR(20) NOT NULL COMMENT '게시판 ID' AFTER `index_no`,
	CHANGE COLUMN `lan` `lan` VARCHAR(10) NOT NULL COMMENT '(사용안함)' AFTER `boardid`,
	CHANGE COLUMN `btype` `btype` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `lan`,
	CHANGE COLUMN `wtype` `wtype` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `btype`,
	CHANGE COLUMN `issecret` `issecret` CHAR(1) NOT NULL COMMENT '(공개여부)' AFTER `wtype`,
	CHANGE COLUMN `mem_idx` `mem_idx` INT(10) UNSIGNED NOT NULL COMMENT '회원구분(0: 비회원 / 1: 회원)' AFTER `issecret`,
	CHANGE COLUMN `mem_name` `mem_name` VARCHAR(80) NOT NULL COMMENT '회원이름' AFTER `mem_idx`,
	CHANGE COLUMN `mem_id` `mem_id` VARCHAR(50) NOT NULL COMMENT '(사용안함)' AFTER `mem_name`,
	CHANGE COLUMN `cates` `cates` VARCHAR(100) NOT NULL COMMENT '(사용안함)' AFTER `mem_id`,
	CHANGE COLUMN `subject` `subject` VARCHAR(200) NOT NULL COMMENT '제목' AFTER `cates`,
	CHANGE COLUMN `subject_part` `subject_part` VARCHAR(200) NOT NULL COMMENT '(사용안함)' AFTER `subject`,
	CHANGE COLUMN `prememo` `prememo` TEXT NOT NULL COMMENT '(사용안함)' AFTER `subject_part`,
	CHANGE COLUMN `memo` `memo` LONGTEXT NOT NULL COMMENT '내용' AFTER `prememo`,
	CHANGE COLUMN `file1` `file1` VARCHAR(100) NOT NULL COMMENT '첨부파일1' AFTER `memo`,
	CHANGE COLUMN `file2` `file2` VARCHAR(100) NOT NULL COMMENT '첨부파일2' AFTER `file1`,
	CHANGE COLUMN `file3` `file3` VARCHAR(250) NOT NULL COMMENT '(첨부파일3)' AFTER `file2`,
	CHANGE COLUMN `file4` `file4` VARCHAR(250) NOT NULL COMMENT '(첨부파일4)' AFTER `file3`,
	CHANGE COLUMN `file5` `file5` VARCHAR(250) NOT NULL COMMENT '(첨부파일5)' AFTER `file4`,
	CHANGE COLUMN `wdate` `wdate` DATETIME NOT NULL COMMENT '등록일' AFTER `file5`,
	CHANGE COLUMN `readcount` `readcount` INT(10) UNSIGNED NOT NULL COMMENT '(조회수)' AFTER `wdate`,
	CHANGE COLUMN `tailcount` `tailcount` INT(10) UNSIGNED NOT NULL COMMENT '(댓글수)' AFTER `readcount`,
	CHANGE COLUMN `tailupdate` `tailupdate` CHAR(10) NOT NULL COMMENT '(댓글업데이트)' AFTER `tailcount`,
	CHANGE COLUMN `loca` `loca` VARCHAR(200) NOT NULL COMMENT '(사용안함)' AFTER `sucount`,
	CHANGE COLUMN `mdate` `mdate` CHAR(10) NOT NULL COMMENT '(등록일)' AFTER `loca`,
	CHANGE COLUMN `isjack` `isjack` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `inpoint`,
	CHANGE COLUMN `islock` `islock` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `nip`,
	CHANGE COLUMN `isdel` `isdel` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제여부(Y:삭제함 / N:삭제안함)' AFTER `islock`,
	CHANGE COLUMN `event_idx` `event_idx` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `isdel`,
	CHANGE COLUMN `market_idx` `market_idx` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `event_idx`,
	CHANGE COLUMN `score` `score` TINYINT(3) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `market_idx`,
	CHANGE COLUMN `hfile` `hfile` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `score`,
	CHANGE COLUMN `wmode` `wmode` CHAR(1) NOT NULL DEFAULT '1' COMMENT '(사용안함)' AFTER `hfile`,
	CHANGE COLUMN `passwds` `passwds` VARCHAR(20) NOT NULL COMMENT '(사용안함)' AFTER `wmode`,
	CHANGE COLUMN `revdate` `revdate` DATETIME NOT NULL COMMENT '(사용안함)' AFTER `passwds`,
	CHANGE COLUMN `langu` `langu` VARCHAR(10) NOT NULL COMMENT '(사용안함)' AFTER `revdate`,
	CHANGE COLUMN `last_idx` `last_idx` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `langu`,
	CHANGE COLUMN `last_idx1` `last_idx1` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `last_idx`,
	CHANGE COLUMN `last_idx2` `last_idx2` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `last_idx1`;

ALTER TABLE `site_board_attach`
	CHANGE COLUMN `board_idx` `board_idx` INT(10) UNSIGNED NOT NULL COMMENT 'site_board.index_no' AFTER `index_no`,
	CHANGE COLUMN `fname` `fname` VARCHAR(100) NOT NULL COMMENT '파일명(서버)' AFTER `board_idx`,
	CHANGE COLUMN `orfname` `orfname` VARCHAR(100) NOT NULL COMMENT '파일명(원본)' AFTER `fname`,
	CHANGE COLUMN `ftype` `ftype` VARCHAR(1) NOT NULL COMMENT '파일타입' AFTER `orfname`,
	CHANGE COLUMN `orders` `orders` INT(10) UNSIGNED NOT NULL COMMENT '파일 업로드 순서' AFTER `ftype`,
	CHANGE COLUMN `tp` `tp` CHAR(1) NOT NULL COMMENT '수정여부 체크' AFTER `orders`;

ALTER TABLE `site_board_conf`
	CHANGE COLUMN `fid` `fid` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `index_no`,
	CHANGE COLUMN `pid` `pid` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `fid`,
	CHANGE COLUMN `board_id` `board_id` VARCHAR(30) NOT NULL COMMENT '(게시판 ID)' AFTER `pid`,
	CHANGE COLUMN `board_name` `board_name` VARCHAR(100) NOT NULL COMMENT '(게시판 이름)' AFTER `board_id`,
	CHANGE COLUMN `skin` `skin` VARCHAR(100) NOT NULL DEFAULT 'default' COMMENT '(스킨)' AFTER `board_name`,
	CHANGE COLUMN `listnum` `listnum` TINYINT(3) UNSIGNED NOT NULL DEFAULT '20' COMMENT '(페이지당 게시물 수)' AFTER `skin`,
	CHANGE COLUMN `listcols` `listcols` TINYINT(4) NOT NULL COMMENT '(사용안함)' AFTER `listnum`,
	CHANGE COLUMN `listcut` `listcut` TINYINT(40) NOT NULL COMMENT '(사용안함)' AFTER `listcols`,
	CHANGE COLUMN `width` `width` INT(10) UNSIGNED NOT NULL DEFAULT '95' COMMENT '(사용안함)' AFTER `listcut`,
	CHANGE COLUMN `width2` `width2` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `width`,
	CHANGE COLUMN `includet` `includet` VARCHAR(200) NOT NULL DEFAULT '../include/boardt.php' COMMENT '(사용안함)' AFTER `width2`,
	CHANGE COLUMN `included` `included` VARCHAR(200) NOT NULL DEFAULT '../include/boardd.php' COMMENT '(사용안함)' AFTER `includet`,
	CHANGE COLUMN `align` `align` VARCHAR(10) NOT NULL DEFAULT 'left' COMMENT '(사용안함)' AFTER `included`,
	CHANGE COLUMN `paddingpx` `paddingpx` TINYINT(3) UNSIGNED NOT NULL DEFAULT '10' COMMENT '(사용안함)' AFTER `align`,
	CHANGE COLUMN `list_priv` `list_priv` TINYINT(3) UNSIGNED NOT NULL DEFAULT '99' COMMENT '(목록권한)' AFTER `paddingpx`,
	CHANGE COLUMN `list_priv_sub` `list_priv_sub` VARCHAR(200) NOT NULL COMMENT '(목록 세부 권한 체크)' AFTER `list_priv`,
	CHANGE COLUMN `write_priv` `write_priv` TINYINT(3) UNSIGNED NOT NULL DEFAULT '20' COMMENT '(글쓰기 권한)' AFTER `list_priv_sub`,
	CHANGE COLUMN `write_priv_sub` `write_priv_sub` VARCHAR(200) NOT NULL COMMENT '(글쓰기 세부 권한 체크)' AFTER `write_priv`,
	CHANGE COLUMN `read_priv_sub` `read_priv_sub` VARCHAR(200) NOT NULL COMMENT '(읽기 세부 권한 체크)' AFTER `read_priv`,
	CHANGE COLUMN `tail_priv` `tail_priv` TINYINT(3) UNSIGNED NOT NULL COMMENT '(댓글 작성 권한)' AFTER `read_priv_sub`,
	CHANGE COLUMN `tail_priv_sub` `tail_priv_sub` VARCHAR(200) NOT NULL COMMENT '(댓글 작성 세부 권한 체크)' AFTER `tail_priv`,
	CHANGE COLUMN `tailcount` `tailcount` INT(10) UNSIGNED NOT NULL COMMENT '(댓글수)' AFTER `tail_priv_sub`,
	CHANGE COLUMN `usenotice` `usenotice` CHAR(1) NOT NULL COMMENT '(공지기능사용)' AFTER `tailcount`,
	CHANGE COLUMN `usesecret` `usesecret` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `usenotice`,
	CHANGE COLUMN `mustsecret` `mustsecret` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `usesecret`,
	CHANGE COLUMN `usesec` `usesec` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `mustsecret`,
	CHANGE COLUMN `mustsec` `mustsec` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `usesec`,
	CHANGE COLUMN `usesu` `usesu` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `mustsec`,
	CHANGE COLUMN `newshow` `newshow` TINYINT(4) NOT NULL COMMENT '(사용안함)' AFTER `usesu`,
	CHANGE COLUMN `newshowimg` `newshowimg` VARCHAR(30) NOT NULL COMMENT '(사용안함)' AFTER `newshow`,
	CHANGE COLUMN `fileimg` `fileimg` VARCHAR(30) NOT NULL COMMENT '(사용안함)' AFTER `newshowimg`,
	CHANGE COLUMN `useeditor` `useeditor` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `fileimg`,
	CHANGE COLUMN `tailsecret` `tailsecret` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `useeditor`,
	CHANGE COLUMN `tailshow` `tailshow` TINYINT(3) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `tailsecret`,
	CHANGE COLUMN `tailshow_color` `tailshow_color` VARCHAR(10) NOT NULL DEFAULT 'red' COMMENT '(사용안함)' AFTER `tailshow`,
	CHANGE COLUMN `readusefile` `readusefile` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `tailshow_color`,
	CHANGE COLUMN `usecate` `usecate` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `readusefile`,
	CHANGE COLUMN `usecate_color` `usecate_color` VARCHAR(10) NOT NULL COMMENT '(사용안함)' AFTER `usecate`,
	CHANGE COLUMN `usecate_memo` `usecate_memo` TEXT NOT NULL COMMENT '(사용안함)' AFTER `usecate_color`,
	CHANGE COLUMN `usescore` `usescore` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `usecate_memo`,
	CHANGE COLUMN `usefile` `usefile` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `usescore`,
	CHANGE COLUMN `useprememo` `useprememo` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `usefile`,
	CHANGE COLUMN `useevent` `useevent` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `useprememo`,
	CHANGE COLUMN `usemempoint` `usemempoint` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `useevent`,
	CHANGE COLUMN `usegoods` `usegoods` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `usemempoint`,
	CHANGE COLUMN `w1point` `w1point` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `usegoods`,
	CHANGE COLUMN `w2point` `w2point` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `w1point`,
	CHANGE COLUMN `w3point` `w3point` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `w2point`,
	CHANGE COLUMN `wmax` `wmax` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `w3point`,
	CHANGE COLUMN `tlimit` `tlimit` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `wmax`,
	CHANGE COLUMN `usejackpot` `usejackpot` CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '(사용안함)' AFTER `tlimit`,
	CHANGE COLUMN `menu_main` `menu_main` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `usejackpot`,
	CHANGE COLUMN `menu_sub` `menu_sub` TINYINT(3) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `menu_main`,
	CHANGE COLUMN `write_return` `write_return` VARCHAR(200) NOT NULL COMMENT '(사용안함)' AFTER `menu_sub`,
	CHANGE COLUMN `basememo` `basememo` LONGTEXT NOT NULL COMMENT '(사용안함)' AFTER `write_return`,
	CHANGE COLUMN `thwidth` `thwidth` SMALLINT(5) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `basememo`,
	CHANGE COLUMN `thheight` `thheight` SMALLINT(5) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `thwidth`,
	CHANGE COLUMN `list_img` `list_img` VARCHAR(100) NOT NULL COMMENT '(사용안함)' AFTER `thheight`,
	CHANGE COLUMN `list_map` `list_map` TEXT NOT NULL COMMENT '(사용안함)' AFTER `list_img`,
	CHANGE COLUMN `list_lan` `list_lan` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `list_map`,
	CHANGE COLUMN `write_img` `write_img` VARCHAR(100) NOT NULL COMMENT '(사용안함)' AFTER `list_lan`,
	CHANGE COLUMN `read_img` `read_img` VARCHAR(100) NOT NULL COMMENT '(사용안함)' AFTER `write_img`,
	CHANGE COLUMN `read_map` `read_map` TEXT NOT NULL COMMENT '(사용안함)' AFTER `read_img`,
	CHANGE COLUMN `tops` `tops` TEXT NOT NULL COMMENT '(사용안함)' AFTER `read_map`,
	CHANGE COLUMN `topuse` `topuse` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `tops`,
	CHANGE COLUMN `snum` `snum` INT(11) NOT NULL COMMENT '(사용안함)' AFTER `topuse`,
	CHANGE COLUMN `spam` `spam` TEXT NOT NULL COMMENT '(사용안함)' AFTER `snum`,
	CHANGE COLUMN `btitlecss` `btitlecss` TEXT NOT NULL COMMENT '(사용안함)' AFTER `spam`,
	CHANGE COLUMN `userev` `userev` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `btitlecss`,
	CHANGE COLUMN `tailwpoint` `tailwpoint` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `userev`,
	CHANGE COLUMN `tailpointt` `tailpointt` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `tailwpoint`,
	CHANGE COLUMN `writetailo` `writetailo` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `tailpointt`,
	CHANGE COLUMN `block1` `block1` TINYINT(4) NOT NULL COMMENT '(사용안함)' AFTER `writetailo`,
	CHANGE COLUMN `block2` `block2` TINYINT(4) NOT NULL COMMENT '(사용안함)' AFTER `block1`;

ALTER TABLE `site_member_card`
	CHANGE COLUMN `mem_idx` `mem_idx` INT(10) UNSIGNED NOT NULL COMMENT 'site_member.index_no' AFTER `index_no`,
	CHANGE COLUMN `cardname` `cardname` VARCHAR(30) NOT NULL DEFAULT '테스트카드' COMMENT '카드명' AFTER `mem_idx`,
	CHANGE COLUMN `cardt` `cardt` CHAR(1) NOT NULL COMMENT '카드타입(1: 개인카드 / 2: 법인카드)' AFTER `cardname`,
	CHANGE COLUMN `datas` `datas` VARCHAR(30) NOT NULL COMMENT '주민번호(최대13자리)' AFTER `cardt`,
	CHANGE COLUMN `fix_key` `fix_key` VARCHAR(50) NOT NULL COMMENT '카드 인증키(최대 24자)' AFTER `datas`,
	CHANGE COLUMN `apply_ymd` `apply_ymd` VARCHAR(14) NOT NULL COMMENT '카드인증일(yyyyMMddHHmmss)' AFTER `fix_key`,
	CHANGE COLUMN `wdate` `wdate` DATETIME NOT NULL COMMENT '등록일' AFTER `apply_ymd`,
	CHANGE COLUMN `isdel` `isdel` CHAR(1) NOT NULL COMMENT '작성여부' AFTER `wdate`;

ALTER TABLE `site_coupen`
	CHANGE COLUMN `img` `img` VARCHAR(100) NOT NULL COMMENT '이미지명' AFTER `index_no`,
	CHANGE COLUMN `coupenname` `coupenname` VARCHAR(50) NOT NULL COMMENT '쿠폰명' AFTER `img`,
	CHANGE COLUMN `sellac` `sellac` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `coupenname`,
	CHANGE COLUMN `actype` `actype` CHAR(1) NOT NULL COMMENT '쿠폰할인종류(1: 금액할인 / 2: %할인)' AFTER `sellac`,
	CHANGE COLUMN `account` `account` INT(10) UNSIGNED NOT NULL COMMENT '할인금액' AFTER `actype`,
	CHANGE COLUMN `maxaccount` `maxaccount` INT(10) UNSIGNED NOT NULL COMMENT '할인최대치' AFTER `account`,
	CHANGE COLUMN `saleper_std1` `saleper_std1` INT(10) UNSIGNED NOT NULL COMMENT '% 할인시 절삭부분(단위)' AFTER `maxaccount`,
	CHANGE COLUMN `saleper_std2` `saleper_std2` CHAR(1) NOT NULL COMMENT '% 할인시 절삭부분(1: 올림 / 2: 반올림 / 3: 내림)' AFTER `saleper_std1`,
	CHANGE COLUMN `usetype` `usetype` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `saleper_std2`,
	CHANGE COLUMN `islogin` `islogin` CHAR(1) NOT NULL COMMENT '배포방법(\' \': 선택안함 / Y: 로그인시 지급 / A: 회원가입시)' AFTER `usetype`,
	CHANGE COLUMN `downs` `downs` VARCHAR(19) NOT NULL COMMENT '배포기간(시작)' AFTER `islogin`,
	CHANGE COLUMN `downe` `downe` VARCHAR(19) NOT NULL COMMENT '배포기간(끝)' AFTER `downs`,
	CHANGE COLUMN `onlyone` `onlyone` CHAR(1) NOT NULL COMMENT '보유개수(Y: 한개만보유가능 / N: 다수보유가능)' AFTER `downe`,
	CHANGE COLUMN `canuseac` `canuseac` INT(10) UNSIGNED NOT NULL COMMENT '사용조건(얼마 이상시에만 사용가능(주문쿠폰에만 해당, 0으로 설정시 조건 없이 사용가능))' AFTER `onlyone`,
	CHANGE COLUMN `used` `used` CHAR(1) NOT NULL COMMENT '사용기간(1: 고정기간, 2: 발행후)' AFTER `canuseac`,
	CHANGE COLUMN `usedays` `usedays` INT(10) UNSIGNED NOT NULL COMMENT '사용기간(2일경우 / 발행 후 ~일 안에 사용)' AFTER `used`,
	CHANGE COLUMN `ending` `ending` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `usedays`,
	CHANGE COLUMN `startdates` `startdates` DATETIME NOT NULL COMMENT '사용기간(고정기간 - 시작)' AFTER `ending`,
	CHANGE COLUMN `enddates` `enddates` DATETIME NOT NULL COMMENT '사용기간(고정기간 - 끝)' AFTER `startdates`,
	CHANGE COLUMN `memo` `memo` TEXT NOT NULL COMMENT '설명' AFTER `isuse`,
	CHANGE COLUMN `usesale` `usesale` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `memo`,
	CHANGE COLUMN `usegsale` `usegsale` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `usesale`,
	CHANGE COLUMN `logingive` `logingive` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `usegsale`,
	CHANGE COLUMN `isserial` `isserial` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '쿠폰종류(N: 일반쿠폰 / 1: 랜덤시리얼 / 2: 시리얼번호지정)' AFTER `logingive`,
	CHANGE COLUMN `serialnum` `serialnum` VARCHAR(50) NOT NULL COMMENT '쿠폰종류(시리얼번호지정일경우 / 지정시리얼번호)' AFTER `isserial`,
	CHANGE COLUMN `fids` `fids` VARCHAR(200) NOT NULL COMMENT '(사용안함)' AFTER `serialnum`,
	CHANGE COLUMN `usesites` `usesites` VARCHAR(200) NOT NULL COMMENT '(사용안함)' AFTER `fids`,
	CHANGE COLUMN `prod2` `prod2` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `prod1`,
	CHANGE COLUMN `usecate` `usecate` VARCHAR(250) NOT NULL COMMENT '(사용안함)' AFTER `prod2`,
	CHANGE COLUMN `nousecate` `nousecate` VARCHAR(250) NOT NULL COMMENT '(사용안함)' AFTER `usecate`,
	CHANGE COLUMN `usegoods` `usegoods` VARCHAR(250) NOT NULL COMMENT '(사용안함)' AFTER `nousecate`,
	CHANGE COLUMN `nousegoods` `nousegoods` VARCHAR(250) NOT NULL COMMENT '(사용안함)' AFTER `usegoods`,
	CHANGE COLUMN `givesave1` `givesave1` CHAR(1) NOT NULL COMMENT '(기본적립금지급여부Y지급N지급안함)' AFTER `nousegoods`,
	CHANGE COLUMN `givesave2` `givesave2` CHAR(1) NOT NULL COMMENT '(추가적립금지급여부Y지급N지급안함)' AFTER `givesave1`,
	CHANGE COLUMN `cars` `cars` TEXT NOT NULL COMMENT '차량정보 직렬화(없을때: N; / 있을때: a:1:{i:0;s:2:"46";})' AFTER `givesave2`,
	CHANGE COLUMN `rentshop` `rentshop` TEXT NOT NULL COMMENT '렌트샵 직렬화(없을때: N; / 있을때: a:1:{i:0;s:2:"31";})' AFTER `cars`;

ALTER TABLE `site_coupen_mem`
	CHANGE COLUMN `mem_idx` `mem_idx` INT(10) UNSIGNED NOT NULL COMMENT 'site_member.index_no' AFTER `index_no`,
	CHANGE COLUMN `coupen_idx` `coupen_idx` INT(10) UNSIGNED NOT NULL COMMENT 'site_coupen.index_no' AFTER `mem_idx`,
	CHANGE COLUMN `coupen_name` `coupen_name` VARCHAR(50) NOT NULL COMMENT 'site_coupen.coupenname' AFTER `coupen_idx`,
	CHANGE COLUMN `mdate` `mdate` CHAR(10) NOT NULL COMMENT '지급일' AFTER `coupen_name`,
	CHANGE COLUMN `sdate` `sdate` DATETIME NOT NULL COMMENT 'site_coupen.startdates' AFTER `mdate`,
	CHANGE COLUMN `edate` `edate` DATETIME NOT NULL COMMENT 'site_coupen.enddates' AFTER `sdate`,
	CHANGE COLUMN `usedate` `usedate` CHAR(10) NOT NULL COMMENT '사용일' AFTER `edate`,
	CHANGE COLUMN `usehour` `usehour` CHAR(8) NOT NULL COMMENT '사용시간' AFTER `usedate`,
	CHANGE COLUMN `actype` `actype` CHAR(1) NOT NULL COMMENT 'site_coupen.actype' AFTER `usehour`,
	CHANGE COLUMN `usetype` `usetype` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `actype`,
	CHANGE COLUMN `account` `account` INT(10) UNSIGNED NOT NULL COMMENT 'site_coupen.account' AFTER `usetype`,
	CHANGE COLUMN `market_idx` `market_idx` INT(10) UNSIGNED NOT NULL COMMENT 'site_marketdb.index_no' AFTER `account`,
	CHANGE COLUMN `mtype` `mtype` CHAR(1) NOT NULL DEFAULT 'A' COMMENT '(기본값A, function.php 에서 M으로 고정중. 따로 쓰이는데는 없음)' AFTER `market_idx`,
	CHANGE COLUMN `mname` `mname` VARCHAR(30) NOT NULL COMMENT '(사용안함)' AFTER `mtype`,
	CHANGE COLUMN `memo` `memo` VARCHAR(200) NOT NULL COMMENT '사유' AFTER `mname`,
	CHANGE COLUMN `canuseac` `canuseac` INT(10) UNSIGNED NOT NULL COMMENT 'site_coupen.canuseac' AFTER `memo`,
	CHANGE COLUMN `log_idx` `log_idx` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `canuseac`,
	CHANGE COLUMN `isout` `isout` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `log_idx`,
	CHANGE COLUMN `usesale` `usesale` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '(사용안함)' AFTER `isout`,
	CHANGE COLUMN `usegsale` `usegsale` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '(사용안함)' AFTER `usesale`,
	CHANGE COLUMN `fids` `fids` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `usegsale`;

ALTER TABLE `site_coupen_serial`
	CHANGE COLUMN `coupen_idx` `coupen_idx` INT(10) UNSIGNED NOT NULL COMMENT 'site_coupen.index_no' AFTER `index_no`,
	CHANGE COLUMN `nums` `nums` VARCHAR(20) NOT NULL COMMENT '쿠폰코드' AFTER `coupen_idx`,
	CHANGE COLUMN `wdate` `wdate` DATETIME NOT NULL COMMENT '작성일' AFTER `nums`,
	CHANGE COLUMN `udate` `udate` DATETIME NOT NULL COMMENT '(사용안함)' AFTER `wdate`,
	CHANGE COLUMN `isuse` `isuse` CHAR(1) NOT NULL COMMENT '사용가능여부(Y: 사용불가 / \' \' : 사용가능)' AFTER `udate`;

ALTER TABLE `site_eng`
	CHANGE COLUMN `car` `car` VARCHAR(100) NULL DEFAULT NULL COMMENT '차량명' AFTER `vclass`,
	CHANGE COLUMN `files` `files` VARCHAR(100) NOT NULL COMMENT '(사용안함)' AFTER `resident`;

ALTER TABLE `site_est`
	CHANGE COLUMN `kinds` `kinds` VARCHAR(50) NOT NULL COMMENT '종류' AFTER `index_no`,
	CHANGE COLUMN `isdeli` `isdeli` VARCHAR(50) NOT NULL COMMENT '방문선택' AFTER `kinds`,
	CHANGE COLUMN `date1` `date1` DATETIME NOT NULL COMMENT '대여일' AFTER `isdeli`,
	CHANGE COLUMN `date2` `date2` DATETIME NOT NULL COMMENT '반납일' AFTER `date1`,
	CHANGE COLUMN `models` `models` VARCHAR(100) NOT NULL COMMENT '차량모델' AFTER `date2`,
	CHANGE COLUMN `name` `name` VARCHAR(50) NOT NULL COMMENT '고객명' AFTER `models`,
	CHANGE COLUMN `cp` `cp` VARCHAR(50) NOT NULL COMMENT '휴대폰번호' AFTER `name`,
	CHANGE COLUMN `email` `email` VARCHAR(100) NOT NULL COMMENT '이메일' AFTER `cp`,
	CHANGE COLUMN `phone` `phone` VARCHAR(50) NOT NULL COMMENT '전화번호' AFTER `email`,
	CHANGE COLUMN `paddr` `paddr` VARCHAR(250) NOT NULL COMMENT '픽업위치' AFTER `phone`,
	CHANGE COLUMN `raddr` `raddr` VARCHAR(250) NOT NULL COMMENT '반납위치' AFTER `paddr`,
	CHANGE COLUMN `memo` `memo` TEXT NOT NULL COMMENT '기타요청사항' AFTER `raddr`,
	CHANGE COLUMN `wdate` `wdate` DATETIME NOT NULL COMMENT '작성일' AFTER `memo`,
	CHANGE COLUMN `wip` `wip` VARCHAR(50) NOT NULL COMMENT '작성 ip' AFTER `wdate`,
	CHANGE COLUMN `adminmemo` `adminmemo` TEXT NOT NULL COMMENT '관리자메모' AFTER `wip`;

ALTER TABLE `site_faq`
	CHANGE COLUMN `fid` `fid` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `index_no`,
	CHANGE COLUMN `cate_idx` `cate_idx` TINYINT(3) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `fid`,
	CHANGE COLUMN `cate` `cate` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '(사용안함)' AFTER `cate_idx`,
	CHANGE COLUMN `isbest` `isbest` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `cate`,
	CHANGE COLUMN `subject` `subject` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '제목' AFTER `isbest`,
	CHANGE COLUMN `memo` `memo` TEXT NOT NULL COMMENT '메모내용' AFTER `subject`,
	CHANGE COLUMN `memo_mode` `memo_mode` CHAR(1) NOT NULL COMMENT '(메모모드(글 작성시 Y로 고정))' AFTER `memo`,
	CHANGE COLUMN `wdate` `wdate` DATETIME NOT NULL COMMENT '작성일' AFTER `memo_mode`,
	CHANGE COLUMN `score` `score` INT(10) UNSIGNED NOT NULL COMMENT '(비중)' AFTER `wdate`;

ALTER TABLE `site_faq_attach`
	CHANGE COLUMN `faq_idx` `faq_idx` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `index_no`,
	CHANGE COLUMN `fname` `fname` VARCHAR(100) NOT NULL COMMENT '(사용안함)' AFTER `faq_idx`,
	CHANGE COLUMN `orfname` `orfname` VARCHAR(100) NOT NULL COMMENT '(사용안함)' AFTER `fname`,
	CHANGE COLUMN `ftype` `ftype` VARCHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `orfname`,
	CHANGE COLUMN `orders` `orders` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `ftype`,
	CHANGE COLUMN `tp` `tp` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `orders`;

ALTER TABLE `site_file`
	CHANGE COLUMN `dt` `dt` DATETIME NULL DEFAULT NULL COMMENT '날짜' AFTER `down`;

ALTER TABLE `site_marketdb`
	CHANGE COLUMN `orderno` `orderno` INT(10) UNSIGNED NOT NULL COMMENT '예약일자(time())' AFTER `index_no`,
	CHANGE COLUMN `mem_idx` `mem_idx` INT(10) UNSIGNED NOT NULL COMMENT '회원(site_member.index_no)' AFTER `orderno`,
	CHANGE COLUMN `mem_idx_sub` `mem_idx_sub` INT(10) UNSIGNED NOT NULL COMMENT '제2운전자 인덱스(site_member.index_no)' AFTER `mem_idx`,
	CHANGE COLUMN `namesub` `namesub` VARCHAR(50) NOT NULL COMMENT '제2운전자 이름' AFTER `mem_idx_sub`,
	CHANGE COLUMN `birthsub` `birthsub` VARCHAR(50) NOT NULL COMMENT '제2운전자 생년월일' AFTER `namesub`,
	CHANGE COLUMN `sexsub` `sexsub` VARCHAR(50) NOT NULL COMMENT '제2운전자 성별(M/F)' AFTER `birthsub`,
	CHANGE COLUMN `cpsub` `cpsub` VARCHAR(50) NOT NULL COMMENT '제2운전자 휴대폰번호' AFTER `sexsub`,
	CHANGE COLUMN `mem_name` `mem_name` VARCHAR(50) NOT NULL COMMENT '예약자 이름(site_member.name)' AFTER `cpsub`,
	CHANGE COLUMN `mem_id` `mem_id` VARCHAR(50) NOT NULL COMMENT '예약자 id(site_member.id)' AFTER `mem_name`,
	CHANGE COLUMN `cp` `cp` VARCHAR(50) NOT NULL COMMENT '예약자 휴대폰번호(site_member.cp)' AFTER `mem_id`,
	CHANGE COLUMN `phone` `phone` VARCHAR(100) NOT NULL COMMENT '(연락처)' AFTER `cp`,
	CHANGE COLUMN `company` `company` VARCHAR(100) NOT NULL COMMENT '(회사)' AFTER `phone`,
	CHANGE COLUMN `car_idx` `car_idx` INT(10) UNSIGNED NOT NULL COMMENT 'site_vehicle.index_no' AFTER `company`,
	CHANGE COLUMN `model_idx` `model_idx` INT(10) UNSIGNED NOT NULL COMMENT 'site_vehicle_std.index_no' AFTER `car_idx`,
	CHANGE COLUMN `retype` `retype` CHAR(1) NOT NULL COMMENT '대여기간(1: 단기대여 / 2: 장기대여)' AFTER `model_idx`,
	CHANGE COLUMN `ddata1` `ddata1` INT(10) UNSIGNED NOT NULL COMMENT '대여기간(단기: 일 / 장기: 개월)' AFTER `retype`,
	CHANGE COLUMN `ddata2` `ddata2` INT(10) UNSIGNED NOT NULL COMMENT '대여기간(단기: 시간 / 장기: 일)' AFTER `ddata1`,
	CHANGE COLUMN `ptype` `ptype` CHAR(1) NOT NULL COMMENT '픽업방법(1: 배달대여 / 2: 지점방문)' AFTER `ddata2`,
	CHANGE COLUMN `rtype` `rtype` CHAR(1) NOT NULL COMMENT '반납방법(1: 동일 지역 반납 / 2: 다른 지역 반납)' AFTER `ptype`,
	CHANGE COLUMN `sdate` `sdate` DATETIME NOT NULL COMMENT '픽업일' AFTER `rtype`,
	CHANGE COLUMN `edate` `edate` DATETIME NOT NULL COMMENT '반납일' AFTER `sdate`,
	CHANGE COLUMN `makedate` `makedate` DATETIME NOT NULL COMMENT '등록일' AFTER `edate`,
	CHANGE COLUMN `cancelrdate` `cancelrdate` DATETIME NOT NULL COMMENT '예약취소 요청일' AFTER `makedate`,
	CHANGE COLUMN `canceldate` `canceldate` DATETIME NOT NULL COMMENT '예약취소 확정일' AFTER `cancelrdate`,
	CHANGE COLUMN `redate` `redate` DATETIME NOT NULL COMMENT '실제반납 일자' AFTER `canceldate`,
	CHANGE COLUMN `dan` `dan` CHAR(1) NOT NULL COMMENT '진행상태(1: 예약확정 / 2: 대여중 / 3: 반납완료 / 4: 취소요청 / 5: 취소완료)' AFTER `redate`,
	CHANGE COLUMN `account` `account` INT(10) UNSIGNED NOT NULL COMMENT '총 결제 요금' AFTER `dan`,
	CHANGE COLUMN `account1` `account1` INT(10) UNSIGNED NOT NULL COMMENT '요금(일 / 월)' AFTER `account`,
	CHANGE COLUMN `account2` `account2` INT(10) UNSIGNED NOT NULL COMMENT '잔여요금(시간(12시간미만 / 일))' AFTER `account1`,
	CHANGE COLUMN `preaccount` `preaccount` INT(10) UNSIGNED NOT NULL COMMENT '보증금' AFTER `account2`,
	CHANGE COLUMN `delac` `delac` INT(10) UNSIGNED NOT NULL COMMENT '배반차료' AFTER `preaccount`,
	CHANGE COLUMN `insu` `insu` CHAR(1) NOT NULL COMMENT '보험종류' AFTER `delac`,
	CHANGE COLUMN `insuac` `insuac` INT(10) UNSIGNED NOT NULL COMMENT '보험금액' AFTER `insu`,
	CHANGE COLUMN `usecoupen` `usecoupen` INT(10) UNSIGNED NOT NULL COMMENT '쿠폰사용(금액)' AFTER `insuac`,
	CHANGE COLUMN `totalaccount` `totalaccount` INT(10) UNSIGNED NOT NULL COMMENT '총대여금액' AFTER `usecoupen`,
	CHANGE COLUMN `addaccount` `addaccount` INT(10) UNSIGNED NOT NULL COMMENT '커미션(딜러 수수료)' AFTER `totalaccount`,
	CHANGE COLUMN `buymethod` `buymethod` CHAR(1) NOT NULL COMMENT '결제 방법(C: 카드결제)' AFTER `addaccount`,
	CHANGE COLUMN `usepoint` `usepoint` INT(10) UNSIGNED NOT NULL COMMENT '포인트 결제' AFTER `buymethod`,
	CHANGE COLUMN `zipcode` `zipcode` CHAR(5) NOT NULL COMMENT '픽업 우편번호' AFTER `usepoint`,
	CHANGE COLUMN `addr1` `addr1` VARCHAR(200) NOT NULL COMMENT '픽업 주소' AFTER `zipcode`,
	CHANGE COLUMN `addr2` `addr2` VARCHAR(200) NOT NULL COMMENT '픽업 상세주소' AFTER `addr1`,
	CHANGE COLUMN `rzipcode` `rzipcode` CHAR(5) NOT NULL COMMENT '반납 우편번호' AFTER `addr2`,
	CHANGE COLUMN `raddr1` `raddr1` VARCHAR(200) NOT NULL COMMENT '반납 주소' AFTER `rzipcode`,
	CHANGE COLUMN `raddr2` `raddr2` VARCHAR(200) NOT NULL COMMENT '반납 상세주소' AFTER `raddr1`,
	CHANGE COLUMN `pdan` `pdan` CHAR(1) NOT NULL COMMENT '취소요청(1: 고객 / 2: 지점)' AFTER `raddr2`,
	CHANGE COLUMN `pid` `pid` CHAR(1) NOT NULL COMMENT '결제경로(A: 어드민 / W: 웹 / M: 모바일)' AFTER `pdan`;

ALTER TABLE `site_marketdb_accounts`
	CHANGE COLUMN `tbtype` `tbtype` CHAR(1) NOT NULL COMMENT '구분(I: 입금 / O: 환불)',
	CHANGE COLUMN `buymethod` `buymethod` CHAR(1) NOT NULL DEFAULT 'C' COMMENT '결제방법(C: 신용카드(기본))' AFTER `tbtype`,
	CHANGE COLUMN `market_idx` `market_idx` INT(10) UNSIGNED NOT NULL COMMENT 'site_marketdb.index_no' AFTER `index_no`,
	CHANGE COLUMN `tmp_idx` `tmp_idx` INT(10) UNSIGNED NOT NULL COMMENT 'site_marketdb_tmp.index_no' AFTER `buymethod`,
	CHANGE COLUMN `account` `account` INT(10) UNSIGNED NOT NULL COMMENT '금액' AFTER `tmp_idx`,
	CHANGE COLUMN `rawdata` `rawdata` TEXT NOT NULL COMMENT '올앳결제정보' AFTER `account`,
	CHANGE COLUMN `wdate` `wdate` DATETIME NOT NULL COMMENT '결제 정보 날짜' AFTER `rawdata`,
	CHANGE COLUMN `isouts` `isouts` INT(10) UNSIGNED NOT NULL COMMENT '환불된금액' AFTER `wdate`,
	CHANGE COLUMN `up_idx` `up_idx` INT(10) UNSIGNED NOT NULL COMMENT '출금시 입금 site_marketdb_accounts.index_no' AFTER `isouts`;

ALTER TABLE `site_marketdb_memo`
	CHANGE COLUMN `cate1` `cate1` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `index_no`,
	CHANGE COLUMN `cate2` `cate2` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `cate1`,
	CHANGE COLUMN `cate3` `cate3` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `cate2`,
	CHANGE COLUMN `mtype` `mtype` CHAR(1) NOT NULL DEFAULT '4' COMMENT '작성형태(1: 인바운드 / 2: 아웃바운드 / 3: 게시물 / 4: 기타)' AFTER `cate3`,
	CHANGE COLUMN `iscl` `iscl` CHAR(1) NOT NULL DEFAULT '2' COMMENT '클레임 유무(1: 클레임 / 2: 일반문의)' AFTER `mtype`,
	CHANGE COLUMN `isouts` `isouts` CHAR(1) NOT NULL COMMENT '아웃콜요청' AFTER `iscl`,
	CHANGE COLUMN `isins` `isins` CHAR(1) NOT NULL COMMENT '본사요청' AFTER `isouts`,
	CHANGE COLUMN `isscore` `isscore` CHAR(1) NOT NULL DEFAULT '1' COMMENT '중요도(1: 낮음 / 2: 보통 / 3: 높음)' AFTER `isins`,
	CHANGE COLUMN `market_idx` `market_idx` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'site_marketdb.index_no' AFTER `isscore`,
	CHANGE COLUMN `wtype` `wtype` VARCHAR(30) NOT NULL DEFAULT '기타' COMMENT '기타' AFTER `market_idx`,
	CHANGE COLUMN `memo` `memo` TEXT NOT NULL COMMENT '메모 내용' AFTER `wtype`,
	CHANGE COLUMN `wdate` `wdate` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '작성일' AFTER `memo`,
	CHANGE COLUMN `writer_idx` `writer_idx` INT(10) UNSIGNED NOT NULL COMMENT 'site_member.index_no' AFTER `wdate`,
	CHANGE COLUMN `writer_s` `writer_s` VARCHAR(100) NOT NULL DEFAULT '' COMMENT 'site_member.name' AFTER `writer_idx`,
	CHANGE COLUMN `isauto` `isauto` CHAR(1) NOT NULL COMMENT '(자동메모 여부, N 값으로 고정)' AFTER `writer_s`,
	CHANGE COLUMN `ischeck` `ischeck` CHAR(1) NOT NULL COMMENT '내관리지정' AFTER `isauto`,
	CHANGE COLUMN `ischeck2` `ischeck2` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `ischeck`,
	CHANGE COLUMN `isstop` `isstop` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `ischeck2`,
	CHANGE COLUMN `up_idx` `up_idx` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `isstop`,
	CHANGE COLUMN `resultdate` `resultdate` DATETIME NOT NULL COMMENT '(사용안함)' AFTER `up_idx`,
	CHANGE COLUMN `resultname` `resultname` VARCHAR(50) NOT NULL COMMENT '(사용안함)' AFTER `resultdate`,
	CHANGE COLUMN `resultmemo` `resultmemo` TEXT NOT NULL COMMENT '(사용안함)' AFTER `resultname`,
	CHANGE COLUMN `isdelay` `isdelay` CHAR(1) NOT NULL COMMENT '(지연안내메모여부)' AFTER `resultmemo`,
	CHANGE COLUMN `delaydate` `delaydate` DATE NOT NULL COMMENT '(지연안내일)' AFTER `isdelay`,
	CHANGE COLUMN `to_idx1` `to_idx1` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `delaydate`,
	CHANGE COLUMN `to_idx2` `to_idx2` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `to_idx1`;

ALTER TABLE `site_marketdb_tmp`
	CHANGE COLUMN `nomem` `nomem` VARCHAR(100) NOT NULL COMMENT '(사용안함)' AFTER `index_no`,
	CHANGE COLUMN `mem_idx` `mem_idx` INT(10) UNSIGNED NOT NULL COMMENT 'site_member.index_no' AFTER `nomem`,
	CHANGE COLUMN `car_idx` `car_idx` INT(10) UNSIGNED NOT NULL COMMENT 'site_vehicle.index_no' AFTER `mem_idx`,
	CHANGE COLUMN `model_idx` `model_idx` INT(10) UNSIGNED NOT NULL COMMENT 'site_vehicle_std.index_no' AFTER `car_idx`,
	CHANGE COLUMN `retype` `retype` CHAR(1) NOT NULL COMMENT '대여기간(1: 단기대여 / 2: 장기대여)' AFTER `model_idx`,
	CHANGE COLUMN `ddata1` `ddata1` INT(10) UNSIGNED NOT NULL COMMENT '대여기간(단기: 일 / 장기: 개월)' AFTER `retype`,
	CHANGE COLUMN `ddata2` `ddata2` INT(10) UNSIGNED NOT NULL COMMENT '대여기간(단기: 시간 / 장기: 일)' AFTER `ddata1`,
	CHANGE COLUMN `ptype` `ptype` CHAR(1) NOT NULL COMMENT '픽업방법(지점방문, 배달대여)' AFTER `ddata2`,
	CHANGE COLUMN `rtype` `rtype` CHAR(1) NOT NULL COMMENT '반납방법(1: 동일지역반납 / 2: 다른지역반납)' AFTER `ptype`,
	CHANGE COLUMN `sdate` `sdate` DATETIME NOT NULL COMMENT '대여일' AFTER `rtype`,
	CHANGE COLUMN `edate` `edate` DATETIME NOT NULL COMMENT '반납일' AFTER `sdate`,
	CHANGE COLUMN `makedate` `makedate` DATETIME NOT NULL COMMENT '등록일' AFTER `edate`,
	CHANGE COLUMN `dan` `dan` CHAR(1) NOT NULL COMMENT '진행상태(1: 예약확정 / 2: 대여중 / 3: 반납완료 / 4: 취소요청 / 5: 취소완료)' AFTER `makedate`,
	CHANGE COLUMN `account` `account` INT(10) UNSIGNED NOT NULL COMMENT '총 결제요금' AFTER `dan`,
	CHANGE COLUMN `account1` `account1` INT(10) UNSIGNED NOT NULL COMMENT '요금(일 / 월)' AFTER `account`,
	CHANGE COLUMN `account2` `account2` INT(10) UNSIGNED NOT NULL COMMENT '잔여요금(시간 / 일)' AFTER `account1`,
	CHANGE COLUMN `preaccount` `preaccount` INT(10) UNSIGNED NOT NULL COMMENT '보증금' AFTER `account2`,
	CHANGE COLUMN `delac` `delac` INT(10) UNSIGNED NOT NULL COMMENT '배반차료' AFTER `preaccount`,
	CHANGE COLUMN `insu` `insu` CHAR(1) NOT NULL COMMENT '보험종류' AFTER `delac`,
	CHANGE COLUMN `insuac` `insuac` INT(10) UNSIGNED NOT NULL COMMENT '보험료' AFTER `insu`,
	CHANGE COLUMN `totalaccount` `totalaccount` INT(10) UNSIGNED NOT NULL COMMENT '최종금액' AFTER `insuac`,
	CHANGE COLUMN `buymethod` `buymethod` CHAR(1) NOT NULL COMMENT '결제방식(C: 신용카드)' AFTER `totalaccount`,
	CHANGE COLUMN `usepoint` `usepoint` INT(10) UNSIGNED NOT NULL COMMENT '포인트 결제' AFTER `buymethod`,
	CHANGE COLUMN `zipcode` `zipcode` CHAR(5) NOT NULL COMMENT '대여 우편번호' AFTER `usepoint`,
	CHANGE COLUMN `addr1` `addr1` VARCHAR(200) NOT NULL COMMENT '대여 주소' AFTER `zipcode`,
	CHANGE COLUMN `addr2` `addr2` VARCHAR(200) NOT NULL COMMENT '대여 상세주소' AFTER `addr1`,
	CHANGE COLUMN `rzipcode` `rzipcode` CHAR(5) NOT NULL COMMENT '반납 우편번호' AFTER `addr2`,
	CHANGE COLUMN `raddr1` `raddr1` VARCHAR(200) NOT NULL COMMENT '반납 주소' AFTER `rzipcode`,
	CHANGE COLUMN `raddr2` `raddr2` VARCHAR(200) NOT NULL COMMENT '반납 세부주소' AFTER `raddr1`;

ALTER TABLE `site_member`
	CHANGE COLUMN `name_etc` `name_etc` VARCHAR(50) NOT NULL COMMENT '(사용안함)' AFTER `name`,
	CHANGE COLUMN `passwd` `passwd` VARCHAR(80) NOT NULL COMMENT '비밀번호' AFTER `id`,
	CHANGE COLUMN `birthtype` `birthtype` CHAR(1) NOT NULL DEFAULT 'S' COMMENT '양력(S),음력(L)' AFTER `birth_day`,
	CHANGE COLUMN `sex` `sex` CHAR(1) NOT NULL DEFAULT 'M' COMMENT '성별(M/F)' AFTER `birthtype`,
	CHANGE COLUMN `cpauth` `cpauth` CHAR(1) NOT NULL COMMENT '(휴대폰인증확인)' AFTER `cp`,
	CHANGE COLUMN `mailser` `mailser` CHAR(1) NOT NULL DEFAULT '' COMMENT '메일 수신여부' AFTER `addr2`,
	CHANGE COLUMN `smsser` `smsser` CHAR(1) NOT NULL DEFAULT '' COMMENT '문자 수신여부' AFTER `mailser`,
	CHANGE COLUMN `pushser` `pushser` CHAR(1) NOT NULL COMMENT '푸시 알림 동의' AFTER `smsser`,
	CHANGE COLUMN `company` `company` VARCHAR(50) NOT NULL COMMENT '소속(법인)' AFTER `pushser`,
	CHANGE COLUMN `businessnum` `businessnum` VARCHAR(50) NOT NULL COMMENT '사업자번호' AFTER `company`,
	CHANGE COLUMN `businessnum_sub` `businessnum_sub` VARCHAR(50) NOT NULL COMMENT '법인번호' AFTER `businessnum`,
	CHANGE COLUMN `paperimg` `paperimg` VARCHAR(50) NOT NULL COMMENT '사업자등록증(파일첨부)' AFTER `businessnum_sub`,
	CHANGE COLUMN `daename` `daename` VARCHAR(50) NOT NULL COMMENT '대표자명' AFTER `paperimg`,
	CHANGE COLUMN `bussinessk1` `bussinessk1` VARCHAR(50) NOT NULL COMMENT '업태' AFTER `daename`,
	CHANGE COLUMN `bussinessk2` `bussinessk2` VARCHAR(50) NOT NULL COMMENT '업종' AFTER `bussinessk1`,
	CHANGE COLUMN `lastlogin` `lastlogin` DATETIME NOT NULL COMMENT '<마지막접속>' AFTER `signdate`,
	CHANGE COLUMN `lastorder` `lastorder` CHAR(10) NOT NULL COMMENT '(사용안함)' AFTER `lastlogin`,
	CHANGE COLUMN `lastip` `lastip` VARCHAR(30) NOT NULL COMMENT '<마지막 ip>' AFTER `lastorder`,
	CHANGE COLUMN `mempoints` `mempoints` INT(10) UNSIGNED NOT NULL COMMENT '잔여포인트' AFTER `lastip`,
	CHANGE COLUMN `memcoins` `memcoins` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `mempoints`,
	CHANGE COLUMN `memaccounts` `memaccounts` INT(10) UNSIGNED NOT NULL COMMENT '(예치금)' AFTER `memcoins`,
	CHANGE COLUMN `memgrade` `memgrade` TINYINT(3) UNSIGNED NOT NULL COMMENT '회원구분 코드(site_member_grades / 10: 멤버사 / 11: 파트너 / 12: 커넥터 / 99: 법인회원 / 100: 일반회원)' AFTER `memaccounts`,
	CHANGE COLUMN `amemgrade` `amemgrade` TINYINT(4) NOT NULL COMMENT '관리자권한코드(site_admin_grade.index_no)' AFTER `memgrade`,
	CHANGE COLUMN `mempriv` `mempriv` VARCHAR(30) NOT NULL COMMENT '(사용안함)' AFTER `amemgrade`,
	CHANGE COLUMN `canconnect` `canconnect` CHAR(1) NOT NULL COMMENT '접속권한(Y: 허용 / N: 거부)' AFTER `mempriv`,
	CHANGE COLUMN `rmemo` `rmemo` TEXT NOT NULL COMMENT '회원정보 내 회원메모(관리자 작성)' AFTER `canconnect`,
	CHANGE COLUMN `enterc` `enterc` VARCHAR(20) NOT NULL COMMENT '<가입종류>' AFTER `rmemo`,
	CHANGE COLUMN `enterk` `enterk` VARCHAR(50) NOT NULL COMMENT '(사용안함)' AFTER `enterc`,
	CHANGE COLUMN `social_type` `social_type` VARCHAR(30) NOT NULL COMMENT 'SNS 로그인(naver. kakao, fb(facebook))' AFTER `enterk`,
	CHANGE COLUMN `social_code` `social_code` VARCHAR(50) NOT NULL COMMENT 'SNS 로그인 코드' AFTER `social_type`,
	CHANGE COLUMN `fid` `fid` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1' COMMENT '(사용안함)' AFTER `social_code`,
	CHANGE COLUMN `pid` `pid` CHAR(1) NOT NULL DEFAULT 'W' COMMENT '가입경로(A: 관리자등록 / W: 웹 / M: 모바일)' AFTER `fid`,
	CHANGE COLUMN `up_idx` `up_idx` INT(10) UNSIGNED NOT NULL COMMENT '법인(소속) site_member.index_no' AFTER `pid`,
	CHANGE COLUMN `up_ok` `up_ok` CHAR(1) NOT NULL COMMENT '소속 가입 요청 승인 여부(N: 미승인)' AFTER `up_idx`;

ALTER TABLE `site_member_addinfo`
	CHANGE COLUMN `mem_idx` `mem_idx` INT(10) UNSIGNED NOT NULL COMMENT '(site_member.index_no)' AFTER `index_no`,
	CHANGE COLUMN `dname1` `dname1` VARCHAR(50) NOT NULL COMMENT '(대표자명)' AFTER `mem_idx`,
	CHANGE COLUMN `dname2` `dname2` VARCHAR(50) NOT NULL COMMENT '(제휴담당자)' AFTER `dname1`,
	CHANGE COLUMN `dname3` `dname3` VARCHAR(50) NOT NULL COMMENT '(경리담당자)' AFTER `dname2`,
	CHANGE COLUMN `dphone1` `dphone1` VARCHAR(20) NOT NULL COMMENT '(대표자 연락처)' AFTER `dname3`,
	CHANGE COLUMN `dphone2` `dphone2` VARCHAR(20) NOT NULL COMMENT '(제휴담당자 연락처)' AFTER `dphone1`,
	CHANGE COLUMN `dphone3` `dphone3` VARCHAR(20) NOT NULL COMMENT '(경리담당자 연락처)' AFTER `dphone2`,
	CHANGE COLUMN `dcp1` `dcp1` VARCHAR(20) NOT NULL COMMENT '(대표자 휴대폰)' AFTER `dphone3`,
	CHANGE COLUMN `dcp2` `dcp2` VARCHAR(20) NOT NULL COMMENT '(제휴담당자 휴대폰)' AFTER `dcp1`,
	CHANGE COLUMN `dcp3` `dcp3` VARCHAR(20) NOT NULL COMMENT '(경리담당자 휴대폰)' AFTER `dcp2`,
	CHANGE COLUMN `demail1` `demail1` VARCHAR(50) NOT NULL COMMENT '(대표자 메일)' AFTER `dcp3`,
	CHANGE COLUMN `demail2` `demail2` VARCHAR(50) NOT NULL COMMENT '(제휴담당자 메일)' AFTER `demail1`,
	CHANGE COLUMN `demail3` `demail3` VARCHAR(50) NOT NULL COMMENT '(경리담당자 메일)' AFTER `demail2`,
	CHANGE COLUMN `dbirth1` `dbirth1` DATE NOT NULL COMMENT '(대표자 생년월일)' AFTER `demail3`,
	CHANGE COLUMN `dbirth2` `dbirth2` DATE NOT NULL COMMENT '(제휴담당자 셍년월일)' AFTER `dbirth1`,
	CHANGE COLUMN `dbirth3` `dbirth3` DATE NOT NULL COMMENT '(경리담당자 생년월일)' AFTER `dbirth2`,
	CHANGE COLUMN `makedate` `makedate` DATE NOT NULL COMMENT '(등록일)' AFTER `dbirth3`,
	CHANGE COLUMN `bank` `bank` VARCHAR(50) NOT NULL COMMENT '(계좌은행)' AFTER `makedate`,
	CHANGE COLUMN `bankaccount` `bankaccount` VARCHAR(50) NOT NULL COMMENT '(계좌번호)' AFTER `bank`,
	CHANGE COLUMN `bankname` `bankname` VARCHAR(50) NOT NULL COMMENT '(예금주)' AFTER `bankaccount`;

ALTER TABLE `site_member_change`
	CHANGE COLUMN `mem_idx` `mem_idx` INT(10) UNSIGNED NOT NULL COMMENT 'site_member.index_no' AFTER `index_no`,
	CHANGE COLUMN `memo` `memo` TEXT NOT NULL COMMENT '변경내용' AFTER `mem_idx`,
	CHANGE COLUMN `wdate` `wdate` INT(11) NOT NULL COMMENT '정보변경일' AFTER `memo`,
	CHANGE COLUMN `ch_name` `ch_name` VARCHAR(20) NOT NULL COMMENT '수정한 사람 이름' AFTER `wdate`;

ALTER TABLE `site_member_grades`
	CHANGE COLUMN `sfid` `sfid` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1' COMMENT '(사용안함)' AFTER `index_no`,
	CHANGE COLUMN `pid` `pid` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `sfid`,
	CHANGE COLUMN `group_idx` `group_idx` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `pid`,
	CHANGE COLUMN `grade_id` `grade_id` TINYINT(3) UNSIGNED NOT NULL COMMENT '(레벨)' AFTER `group_idx`,
	CHANGE COLUMN `grade_name` `grade_name` VARCHAR(50) NOT NULL COMMENT '(등급명)' AFTER `grade_id`,
	CHANGE COLUMN `grade_saveper` `grade_saveper` INT(10) UNSIGNED NOT NULL COMMENT '(추가적립율)' AFTER `grade_name`,
	CHANGE COLUMN `grade_sv1` `grade_sv1` TINYINT(4) NOT NULL COMMENT '(사용안함)' AFTER `grade_saveper`,
	CHANGE COLUMN `grade_sv2` `grade_sv2` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `grade_sv1`,
	CHANGE COLUMN `grade_savecau` `grade_savecau` VARCHAR(10) NOT NULL COMMENT '(사용안함)' AFTER `grade_sv2`,
	CHANGE COLUMN `grade_stand` `grade_stand` INT(10) UNSIGNED NOT NULL COMMENT '(할인률(~원 이상 구매시))' AFTER `grade_savecau`,
	CHANGE COLUMN `grade_discount` `grade_discount` INT(11) NOT NULL COMMENT '(할인률(%))' AFTER `grade_stand`,
	CHANGE COLUMN `grade_canup` `grade_canup` CHAR(1) NOT NULL COMMENT '(자동등급조절(Y: 사용 / N: 사용안함))' AFTER `grade_discount`,
	CHANGE COLUMN `grade_up` `grade_up` INT(10) UNSIGNED NOT NULL COMMENT '(등업기준(~원 이상 구매시))' AFTER `grade_canup`,
	CHANGE COLUMN `grade_birth` `grade_birth` INT(10) UNSIGNED NOT NULL COMMENT '(등급별생일쿠폰)' AFTER `grade_up`,
	CHANGE COLUMN `enterb` `enterb` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `grade_birth`,
	CHANGE COLUMN `icon` `icon` VARCHAR(30) NULL DEFAULT NULL COMMENT '(아이콘)' AFTER `enterb`,
	CHANGE COLUMN `iconl` `iconl` VARCHAR(50) NOT NULL COMMENT '(아이콘)' AFTER `icon`,
	CHANGE COLUMN `up_idx` `up_idx` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `iconl`,
	CHANGE COLUMN `up_stand` `up_stand` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `up_idx`,
	CHANGE COLUMN `procode` `procode` VARCHAR(30) NOT NULL COMMENT '(프로모션코드)' AFTER `up_stand`;

ALTER TABLE `site_member_group`
	CHANGE COLUMN `groupname` `groupname` VARCHAR(30) NOT NULL COMMENT '(회원그룹이름)' AFTER `index_no`,
	CHANGE COLUMN `grouptype` `grouptype` CHAR(1) NOT NULL COMMENT '(그룹타입)' AFTER `groupname`,
	CHANGE COLUMN `member_joinpoint` `member_joinpoint` INT(10) UNSIGNED NOT NULL COMMENT '(회원가입적립금)' AFTER `grouptype`,
	CHANGE COLUMN `member_joinpoint_msg` `member_joinpoint_msg` VARCHAR(100) NOT NULL COMMENT '(회원가입적립금 내역 메세지)' AFTER `member_joinpoint`,
	CHANGE COLUMN `member_joingrade` `member_joingrade` INT(10) UNSIGNED NOT NULL COMMENT '(회원가입등급)' AFTER `member_joinpoint_msg`,
	CHANGE COLUMN `member_joincoupen` `member_joincoupen` VARCHAR(50) NOT NULL COMMENT '(회원가입쿠폰)' AFTER `member_joingrade`,
	CHANGE COLUMN `member_birthday` `member_birthday` TINYINT(3) UNSIGNED NOT NULL COMMENT '(생일쿠폰지급일시)' AFTER `member_joincoupen`,
	CHANGE COLUMN `member_birthcoupen` `member_birthcoupen` INT(10) UNSIGNED NOT NULL COMMENT '(회원생일쿠폰 고유번호)' AFTER `member_birthday`,
	CHANGE COLUMN `member_joinsms` `member_joinsms` CHAR(1) NOT NULL COMMENT '(가입시문자)' AFTER `member_birthcoupen`,
	CHANGE COLUMN `order_point_std` `order_point_std` INT(10) UNSIGNED NOT NULL COMMENT '(예약시적립금)' AFTER `member_joinsms`,
	CHANGE COLUMN `order_min_point` `order_min_point` INT(10) UNSIGNED NOT NULL COMMENT '(예약시적립금 사용조건(최소 금액))' AFTER `order_point_std`,
	CHANGE COLUMN `order_max_point1` `order_max_point1` INT(10) UNSIGNED NOT NULL COMMENT '(예약시적립금 사용조건(최대 금액))' AFTER `order_min_point`,
	CHANGE COLUMN `order_max_point2` `order_max_point2` CHAR(1) NOT NULL COMMENT '(적립금사용최대치1:원/2:%)' AFTER `order_max_point1`,
	CHANGE COLUMN `order_point_cnt` `order_point_cnt` TINYINT(3) UNSIGNED NOT NULL COMMENT '(예약 횟수)' AFTER `order_max_point2`,
	CHANGE COLUMN `autogradeup` `autogradeup` CHAR(1) NOT NULL COMMENT '(자동등업)' AFTER `order_point_cnt`,
	CHANGE COLUMN `gradeupstd` `gradeupstd` CHAR(1) NOT NULL COMMENT '(자동등업주기)' AFTER `autogradeup`,
	CHANGE COLUMN `gradeupstddays` `gradeupstddays` TINYINT(3) UNSIGNED NOT NULL COMMENT '(등업사용데이터(개월))' AFTER `gradeupstd`,
	CHANGE COLUMN `joincheck1` `joincheck1` CHAR(1) NOT NULL COMMENT '(닉네임중복확인)' AFTER `gradeupstddays`,
	CHANGE COLUMN `joincheck2` `joincheck2` CHAR(1) NOT NULL COMMENT '(휴대폰중복확인)' AFTER `joincheck1`,
	CHANGE COLUMN `joincheck3` `joincheck3` CHAR(1) NOT NULL COMMENT '(이메일중복확인)' AFTER `joincheck2`,
	CHANGE COLUMN `userevsp` `userevsp` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `joincheck3`,
	CHANGE COLUMN `modnick` `modnick` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `userevsp`,
	CHANGE COLUMN `modbirth` `modbirth` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `modnick`,
	CHANGE COLUMN `lastgradeup` `lastgradeup` CHAR(10) NOT NULL COMMENT '(사용안함)' AFTER `modbirth`,
	CHANGE COLUMN `usecheck` `usecheck` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '(사용안함)' AFTER `lastgradeup`,
	CHANGE COLUMN `checkreward` `checkreward` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `usecheck`,
	CHANGE COLUMN `checkrewardg` `checkrewardg` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `checkreward`,
	CHANGE COLUMN `checkstd` `checkstd` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `checkrewardg`,
	CHANGE COLUMN `checkstddays` `checkstddays` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `checkstd`,
	CHANGE COLUMN `saveaddp` `saveaddp` CHAR(1) NOT NULL COMMENT '(추가적립금기준)' AFTER `checkstddays`;

ALTER TABLE `site_member_license`
	CHANGE COLUMN `mem_idx` `mem_idx` INT(10) UNSIGNED NOT NULL COMMENT 'site_member.index_no' AFTER `index_no`,
	CHANGE COLUMN `kinds` `kinds` VARCHAR(10) NOT NULL COMMENT '면허종류(FL: 1종 대형 / FN: 1종 보통 / SN: 2종 보통)' AFTER `mem_idx`,
	CHANGE COLUMN `codes` `codes` VARCHAR(10) NOT NULL COMMENT '면허지역' AFTER `kinds`,
	CHANGE COLUMN `nums` `nums` VARCHAR(30) NOT NULL COMMENT '면허번호' AFTER `codes`,
	CHANGE COLUMN `date1` `date1` VARCHAR(10) NOT NULL COMMENT '갱신기간' AFTER `nums`,
	CHANGE COLUMN `date2` `date2` VARCHAR(10) NOT NULL COMMENT '발급일' AFTER `date1`,
	CHANGE COLUMN `wdate` `wdate` DATETIME NOT NULL COMMENT '운전면허정보 등록일' AFTER `date2`;

ALTER TABLE `site_member_points`
	CHANGE COLUMN `market_idx` `market_idx` INT(10) UNSIGNED NOT NULL COMMENT '(site_marketdb.index_no)' AFTER `index_no`,
	CHANGE COLUMN `board_idx` `board_idx` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `market_idx`,
	CHANGE COLUMN `mem_idx` `mem_idx` INT(10) UNSIGNED NOT NULL COMMENT '(site_member.index_no)' AFTER `board_idx`,
	CHANGE COLUMN `income` `income` INT(10) UNSIGNED NOT NULL COMMENT '(적립액)' AFTER `mem_idx`,
	CHANGE COLUMN `outcome` `outcome` INT(10) UNSIGNED NOT NULL COMMENT '(사용액)' AFTER `income`,
	CHANGE COLUMN `total` `total` INT(10) UNSIGNED NOT NULL COMMENT '(잔액)' AFTER `outcome`,
	CHANGE COLUMN `oincome` `oincome` FLOAT UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `total`,
	CHANGE COLUMN `ooutcome` `ooutcome` FLOAT UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `oincome`,
	CHANGE COLUMN `ototal` `ototal` FLOAT UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `ooutcome`,
	CHANGE COLUMN `memo` `memo` TEXT NOT NULL COMMENT '(변경사유)' AFTER `ototal`,
	CHANGE COLUMN `wdate_s` `wdate_s` VARCHAR(10) NOT NULL COMMENT '(변경일자)' AFTER `memo`,
	CHANGE COLUMN `hour_s` `hour_s` VARCHAR(8) NOT NULL COMMENT '(변경시간)' AFTER `wdate_s`,
	CHANGE COLUMN `isauto` `isauto` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `hour_s`,
	CHANGE COLUMN `ch_name` `ch_name` VARCHAR(20) NOT NULL COMMENT '(처리자)' AFTER `isauto`,
	CHANGE COLUMN `codes` `codes` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `ch_name`;

ALTER TABLE `site_nows`
	CHANGE COLUMN `member_idx` `member_idx` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'site_member.index_no' AFTER `keys_v`,
	CHANGE COLUMN `end_time` `end_time` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '세션 종료시간' AFTER `member_idx`;

ALTER TABLE `site_qna`
	CHANGE COLUMN `btype` `btype` TINYINT(4) NOT NULL COMMENT '(2 값으로 고정)' AFTER `index_no`,
	CHANGE COLUMN `goods_idx` `goods_idx` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `btype`,
	CHANGE COLUMN `market_idx` `market_idx` INT(10) NOT NULL COMMENT '(사용안함)' AFTER `goods_idx`,
	CHANGE COLUMN `cate` `cate` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '(사용안함)' AFTER `market_idx`,
	CHANGE COLUMN `issec` `issec` CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '(사용안함)' AFTER `cate`,
	CHANGE COLUMN `mem_idx` `mem_idx` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'site_member.index_no' AFTER `issec`,
	CHANGE COLUMN `mem_name` `mem_name` VARCHAR(30) NOT NULL COMMENT 'site_member.name' AFTER `mem_idx`,
	CHANGE COLUMN `mem_id` `mem_id` VARCHAR(50) NOT NULL COMMENT '(site_member.id)' AFTER `mem_name`,
	CHANGE COLUMN `cp` `cp` VARCHAR(30) NOT NULL COMMENT '휴대폰번호' AFTER `mem_id`,
	CHANGE COLUMN `email` `email` VARCHAR(100) NOT NULL COMMENT '(QNA 이메일)' AFTER `cp`,
	CHANGE COLUMN `subject` `subject` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '제목' AFTER `email`,
	CHANGE COLUMN `memo` `memo` TEXT NOT NULL COMMENT '내용' AFTER `subject`,
	CHANGE COLUMN `file1` `file1` VARCHAR(100) NOT NULL COMMENT '(사용안함)' AFTER `memo`,
	CHANGE COLUMN `file2` `file2` VARCHAR(100) NOT NULL COMMENT '(사용안함)' AFTER `file1`,
	CHANGE COLUMN `wdate` `wdate` DATETIME NOT NULL COMMENT '작성일' AFTER `file2`,
	CHANGE COLUMN `nip` `nip` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '(사용안함)' AFTER `wdate`,
	CHANGE COLUMN `result` `result` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '답변여부(Y/N)' AFTER `nip`,
	CHANGE COLUMN `resultwriter` `resultwriter` VARCHAR(20) NOT NULL COMMENT '답변작성자' AFTER `result`,
	CHANGE COLUMN `resultmemo` `resultmemo` TEXT NOT NULL COMMENT '답변내용' AFTER `resultwriter`,
	CHANGE COLUMN `resultdate` `resultdate` DATETIME NOT NULL COMMENT '답변작성일' AFTER `resultmemo`,
	CHANGE COLUMN `isdel` `isdel` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제여부(Y/N)' AFTER `resultdate`,
    CHANGE COLUMN `passwds` `passwds` VARCHAR(250) NOT NULL COMMENT '(사용안함)' AFTER `isdel`,
    CHANGE COLUMN `isjak` `isjak` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `passwds`,
    CHANGE COLUMN `delname` `delname` VARCHAR(30) NOT NULL COMMENT '(사용안함)' AFTER `isjak`,
    CHANGE COLUMN `last_idx` `last_idx` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `delname`,
    CHANGE COLUMN `last_idx1` `last_idx1` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `last_idx`,
    CHANGE COLUMN `last_idx2` `last_idx2` VARCHAR(20) NOT NULL COMMENT '(사용안함)' AFTER `last_idx1`,
    CHANGE COLUMN `fid` `fid` INT(10) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `last_idx2`,
    CHANGE COLUMN `pid` `pid` INT(10) UNSIGNED NOT NULL COMMENT '작성위치(W: 웹 / M: 모바일)' AFTER `fid`,
    CHANGE COLUMN `language` `language` VARCHAR(3) NOT NULL DEFAULT 'KO' COMMENT '언어(ex: KO)' AFTER `pid`;

ALTER TABLE `site_rentshop`
	CHANGE COLUMN `mem_idx` `mem_idx` INT(10) UNSIGNED NOT NULL COMMENT 'site_member.index_no' AFTER `index_no`,
	CHANGE COLUMN `name` `name` VARCHAR(50) NOT NULL COMMENT '법인명(렌터카명)' AFTER `mem_idx`,
	CHANGE COLUMN `nickname` `nickname` VARCHAR(50) NOT NULL COMMENT '닉네임' AFTER `name`,
	CHANGE COLUMN `totalcar` `totalcar` INT(10) UNSIGNED NOT NULL COMMENT '총차량대수' AFTER `nickname`,
	CHANGE COLUMN `sido` `sido` VARCHAR(50) NOT NULL COMMENT '(사용안함)' AFTER `totalcar`,
	CHANGE COLUMN `gugun` `gugun` VARCHAR(50) NOT NULL COMMENT '(사용안함)' AFTER `sido`,
	CHANGE COLUMN `zipcode` `zipcode` CHAR(5) NOT NULL COMMENT '우편번호' AFTER `gugun`,
	CHANGE COLUMN `addr1` `addr1` VARCHAR(200) NOT NULL COMMENT '주소' AFTER `zipcode`,
	CHANGE COLUMN `addr2` `addr2` VARCHAR(200) NOT NULL COMMENT '상세주소' AFTER `addr1`,
	CHANGE COLUMN `latlng` `latlng` POINT NULL DEFAULT NULL COMMENT '위도경도' AFTER `addr2`,
	CHANGE COLUMN `dname1` `dname1` VARCHAR(50) NOT NULL COMMENT '대표자명' AFTER `latlng`,
	CHANGE COLUMN `dname2` `dname2` VARCHAR(50) NOT NULL COMMENT '제휴담당자' AFTER `dname1`,
	CHANGE COLUMN `dname3` `dname3` VARCHAR(50) NOT NULL COMMENT '경리담당자' AFTER `dname2`,
	CHANGE COLUMN `dphone1` `dphone1` VARCHAR(20) NOT NULL COMMENT '대표자 번호' AFTER `dname3`,
	CHANGE COLUMN `dphone2` `dphone2` VARCHAR(20) NOT NULL COMMENT '제휴담당자 번호' AFTER `dphone1`,
	CHANGE COLUMN `dphone3` `dphone3` VARCHAR(20) NOT NULL COMMENT '경리담당자 번호' AFTER `dphone2`,
	CHANGE COLUMN `dcp1` `dcp1` VARCHAR(20) NOT NULL COMMENT '대표자 휴대폰번호' AFTER `dphone3`,
	CHANGE COLUMN `dcp2` `dcp2` VARCHAR(20) NOT NULL COMMENT '제휴담당자 휴대폰번호' AFTER `dcp1`,
	CHANGE COLUMN `dcp3` `dcp3` VARCHAR(20) NOT NULL COMMENT '제휴담당자 휴대폰번호' AFTER `dcp2`,
	CHANGE COLUMN `demail1` `demail1` VARCHAR(50) NOT NULL COMMENT '대표자 이메일' AFTER `dcp3`,
	CHANGE COLUMN `demail2` `demail2` VARCHAR(50) NOT NULL COMMENT '제휴담당자 이메일' AFTER `demail1`,
	CHANGE COLUMN `demail3` `demail3` VARCHAR(50) NOT NULL COMMENT '경리담당자 이메일' AFTER `demail2`,
	CHANGE COLUMN `dbirth1` `dbirth1` DATE NOT NULL COMMENT '대표자 생년월일' AFTER `demail3`,
	CHANGE COLUMN `dbirth2` `dbirth2` DATE NOT NULL COMMENT '제휴담당자 생년월일' AFTER `dbirth1`,
	CHANGE COLUMN `dbirth3` `dbirth3` DATE NOT NULL COMMENT '경리담당자 생년월일' AFTER `dbirth2`,
	CHANGE COLUMN `wtime` `wtime` INT(11) NOT NULL COMMENT '반납정비시간' AFTER `dbirth3`,
	CHANGE COLUMN `s1time1` `s1time1` CHAR(5) NOT NULL COMMENT '평일 영업시간( ~시부터)' AFTER `wtime`,
	CHANGE COLUMN `s1time2` `s1time2` CHAR(5) NOT NULL COMMENT '평일 영업시간(~시까지)' AFTER `s1time1`,
	CHANGE COLUMN `s2time1` `s2time1` CHAR(5) NOT NULL COMMENT '주말/공휴일 영업시간(~시부터)' AFTER `s1time2`,
	CHANGE COLUMN `s2time2` `s2time2` CHAR(5) NOT NULL COMMENT '주말/공휴일 영업시간(~시까지)' AFTER `s2time1`,
	CHANGE COLUMN `d1time1` `d1time1` VARCHAR(10) NOT NULL COMMENT '평일 배반차가능시간(~시부터)' AFTER `s2time2`,
	CHANGE COLUMN `d1time2` `d1time2` VARCHAR(10) NOT NULL COMMENT '평일 배반차가능시간(~시까지)' AFTER `d1time1`,
	CHANGE COLUMN `d2time1` `d2time1` VARCHAR(10) NOT NULL COMMENT '주말/공휴일 영업시간(~시부터)' AFTER `d1time2`,
	CHANGE COLUMN `d2time2` `d2time2` VARCHAR(10) NOT NULL COMMENT '주말/공휴일 영업시간(~시까지)' AFTER `d2time1`,
	CHANGE COLUMN `wtime1` `wtime1` INT(11) NOT NULL COMMENT '예약대기시간(지점방문)' AFTER `d2time2`,
	CHANGE COLUMN `wtime2` `wtime2` INT(10) UNSIGNED NOT NULL COMMENT '예약대기시간(배달대여)' AFTER `wtime1`,
	CHANGE COLUMN `makedate` `makedate` DATE NOT NULL COMMENT '등록일' AFTER `wtime2`,
	CHANGE COLUMN `memo` `memo` TEXT NOT NULL COMMENT '회사특징 메모' AFTER `makedate`,
	CHANGE COLUMN `isok` `isok` CHAR(1) NOT NULL COMMENT '사용인증(Y:허가 / N:비허가)' AFTER `memo`,
	CHANGE COLUMN `per1` `per1` INT(10) UNSIGNED NOT NULL COMMENT '수수료_App/Web (%)' AFTER `isok`,
	CHANGE COLUMN `per2` `per2` INT(10) UNSIGNED NOT NULL COMMENT '수수료_인트라넷(%)' AFTER `per1`,
	CHANGE COLUMN `bank` `bank` VARCHAR(50) NOT NULL COMMENT '은행명' AFTER `per2`,
	CHANGE COLUMN `bankaccount` `bankaccount` VARCHAR(50) NOT NULL COMMENT '은행계좌' AFTER `bank`,
	CHANGE COLUMN `bankname` `bankname` VARCHAR(50) NOT NULL COMMENT '예금주' AFTER `bankaccount`;

ALTER TABLE `site_rentshop_loca`
	CHANGE COLUMN `com_idx` `com_idx` INT(10) UNSIGNED NOT NULL COMMENT '	CHANGE COLUMN `bankname` `bankname` VARCHAR(50) NOT NULL COMMENT \'예금주\' AFTER `bankaccount`;' AFTER `index_no`,
	CHANGE COLUMN `stype` `stype` CHAR(1) NOT NULL COMMENT '1: 단기 / 2: 월장기' AFTER `com_idx`,
	CHANGE COLUMN `loca1` `loca1` VARCHAR(30) NOT NULL COMMENT '지역코드2자리' AFTER `stype`,
	CHANGE COLUMN `loca2` `loca2` VARCHAR(30) NOT NULL COMMENT '지역코드(세부)5자리' AFTER `loca1`,
	CHANGE COLUMN `tmp` `tmp` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `loca2`;

ALTER TABLE `site_rentshop_off`
	CHANGE COLUMN `com_idx` `com_idx` INT(10) UNSIGNED NOT NULL COMMENT 'site_rentshop.index_no' AFTER `index_no`,
	CHANGE COLUMN `sdate` `sdate` DATE NOT NULL COMMENT '휴차시작일' AFTER `com_idx`,
	CHANGE COLUMN `edate` `edate` DATE NOT NULL COMMENT '휴차끝' AFTER `sdate`,
	CHANGE COLUMN `wdate` `wdate` DATETIME NOT NULL COMMENT '등록일' AFTER `edate`;

ALTER TABLE `site_requ`
	CHANGE COLUMN `email` `email` VARCHAR(100) NOT NULL COMMENT '(작성자 이메일)' AFTER `index_no`,
	CHANGE COLUMN `phone` `phone` VARCHAR(50) NOT NULL COMMENT '(작성자 휴대폰번호)' AFTER `email`,
	CHANGE COLUMN `subject` `subject` VARCHAR(200) NOT NULL COMMENT '(제목)' AFTER `phone`,
	CHANGE COLUMN `memo` `memo` TEXT NOT NULL COMMENT '(내용)' AFTER `subject`,
	CHANGE COLUMN `wdate` `wdate` DATETIME NOT NULL COMMENT '(작성일)' AFTER `memo`,
	CHANGE COLUMN `wip` `wip` VARCHAR(30) NOT NULL COMMENT '(작성ip)' AFTER `wdate`,
	CHANGE COLUMN `adminmemo` `adminmemo` TEXT NOT NULL COMMENT '(관리자답변)' AFTER `wip`;

ALTER TABLE `site_situation_msg`
	CHANGE COLUMN `keyidx` `keyidx` INT(11) NOT NULL COMMENT 'site_situation_std.keycode' AFTER `index_no`,
	CHANGE COLUMN `title` `title` VARCHAR(250) NOT NULL COMMENT '제목' AFTER `keyidx`,
	CHANGE COLUMN `isuse` `isuse` CHAR(1) NOT NULL COMMENT '사용여부(Y/N)' AFTER `title`,
	CHANGE COLUMN `usesms` `usesms` CHAR(1) NOT NULL COMMENT 'SMS 사용여부(Y/N)' AFTER `isuse`,
	CHANGE COLUMN `uselms` `uselms` CHAR(1) NOT NULL COMMENT 'LMS 사용여부(Y/N)' AFTER `usesms`,
	CHANGE COLUMN `useapp` `useapp` CHAR(1) NOT NULL COMMENT 'APP 사용여부(Y/N)' AFTER `uselms`,
	CHANGE COLUMN `usealim` `usealim` CHAR(1) NOT NULL COMMENT '알림톡 사용여부(Y/N)' AFTER `useapp`,
	CHANGE COLUMN `memo` `memo` TEXT NOT NULL COMMENT '문자 내용' AFTER `usealim`;

ALTER TABLE `site_situation_std`
	CHANGE COLUMN `keycode` `keycode` TINYINT(3) UNSIGNED NOT NULL COMMENT '<코드>' AFTER `index_no`,
	CHANGE COLUMN `name` `name` VARCHAR(100) NOT NULL COMMENT '<제목>' AFTER `keycode`;

ALTER TABLE `site_vehicle`
	CHANGE COLUMN `com_idx` `com_idx` INT(10) UNSIGNED NOT NULL COMMENT 'site_rentshop.index_no' AFTER `index_no`,
	CHANGE COLUMN `model_idx` `model_idx` INT(10) UNSIGNED NOT NULL COMMENT 'site_vehicle_std.index_no' AFTER `com_idx`,
	CHANGE COLUMN `carnum` `carnum` VARCHAR(10) NOT NULL COMMENT '차량번호' AFTER `outdate`,
	CHANGE COLUMN `color` `color` VARCHAR(10) NOT NULL COMMENT '색상' AFTER `rundistan`,
	CHANGE COLUMN `rentage` `rentage` CHAR(1) NOT NULL COMMENT '연령선택(A:만21세이상 / B:만26세이상)' AFTER `color`,
	CHANGE COLUMN `nosmoke` `nosmoke` CHAR(1) NOT NULL COMMENT '금연차(Y/\' \')' AFTER `rentage`,
	CHANGE COLUMN `price_idx` `price_idx` INT(11) NOT NULL DEFAULT '0' COMMENT '단기요금제(site_vehicle_price.idx)' AFTER `nosmoke`,
	CHANGE COLUMN `price_longterm_idx` `price_longterm_idx` INT(11) NOT NULL DEFAULT '0' COMMENT '장기요금제(site_vehicle_price_longterm.idx)' AFTER `price_idx`,
	CHANGE COLUMN `insu_per` `insu_per` VARCHAR(100) NOT NULL COMMENT '보험사항_대인: 무한(고정)' AFTER `price_longterm_idx`,
	CHANGE COLUMN `insu_goods` `insu_goods` INT(11) NOT NULL COMMENT '보험사항_대물' AFTER `insu_per`,
	CHANGE COLUMN `insu_self` `insu_self` INT(11) NOT NULL COMMENT '보험사항_자손' AFTER `insu_goods`,
	CHANGE COLUMN `liscense_limit` `liscense_limit` INT(11) NOT NULL DEFAULT '0' COMMENT '면허제한(~년 이상)' AFTER `insu_self`,
	CHANGE COLUMN `wdate` `wdate` DATETIME NOT NULL COMMENT '등록일' AFTER `liscense_limit`,
	CHANGE COLUMN `moddate` `moddate` DATETIME NOT NULL COMMENT '(사용안함)' AFTER `wdate`,
	CHANGE COLUMN `ceiling_type` `ceiling_type` VARCHAR(50) NOT NULL COMMENT '(사용안함)' AFTER `moddate`,
	CHANGE COLUMN `seat_type` `seat_type` VARCHAR(50) NOT NULL COMMENT '(사용안함)' AFTER `ceiling_type`,
	CHANGE COLUMN `hipass_installed` `hipass_installed` VARCHAR(50) NOT NULL COMMENT '(사용안함)' AFTER `seat_type`,
	CHANGE COLUMN `blackbox_installed` `blackbox_installed` VARCHAR(50) NOT NULL COMMENT '(사용안함)' AFTER `hipass_installed`,
	CHANGE COLUMN `isdel` `isdel` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제여부(Y/N)' AFTER `blackbox_installed`,
	CHANGE COLUMN `cardan` `cardan` CHAR(1) NOT NULL COMMENT '차량상태(\' \' : 대기중 / 1: 예약중 / 2 : 대여중)' AFTER `isdel`,
	CHANGE COLUMN `last_idx` `last_idx` INT(10) UNSIGNED NOT NULL COMMENT '<미확인>' AFTER `cardan`;

ALTER TABLE `site_vehicle_attribute`
	CHANGE COLUMN `ttype` `ttype` CHAR(1) NOT NULL COMMENT '1:제조사 / 2: 차량등급 / 3: 연료타입 / 4: 색상' AFTER `index_no`,
	CHANGE COLUMN `sname` `sname` VARCHAR(50) NOT NULL COMMENT '명칭' AFTER `ttype`,
	CHANGE COLUMN `dtype` `dtype` VARCHAR(10) NOT NULL COMMENT '(사용안함)' AFTER `sname`;

ALTER TABLE `site_vehicle_off`
	CHANGE COLUMN `index_no` `index_no` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
	CHANGE COLUMN `car_idx` `car_idx` INT(10) UNSIGNED NOT NULL COMMENT 'site_vehicle.index_no' AFTER `index_no`,
	CHANGE COLUMN `offsdate` `offsdate` DATE NOT NULL COMMENT '휴차일 시작' AFTER `car_idx`,
	CHANGE COLUMN `offedate` `offedate` DATE NOT NULL COMMENT '휴차일 끝' AFTER `offsdate`,
	CHANGE COLUMN `wdate` `wdate` DATETIME NOT NULL COMMENT '등록일' AFTER `offedate`;

ALTER TABLE `site_vehicle_opt`
	CHANGE COLUMN `car_idx` `car_idx` INT(10) UNSIGNED NOT NULL COMMENT 'site_vehicle.index_no' AFTER `index_no`,
	CHANGE COLUMN `op_idx` `op_idx` INT(10) UNSIGNED NOT NULL COMMENT 'site_vehicle_opt_std.index_no' AFTER `car_idx`,
	CHANGE COLUMN `op_name` `op_name` VARCHAR(30) NOT NULL COMMENT 'site_vehicle_opt_std.name' AFTER `op_idx`,
	CHANGE COLUMN `op_data` `op_data` VARCHAR(50) NOT NULL COMMENT '상세' AFTER `op_name`;

ALTER TABLE `site_vehicle_opt_std`
	CHANGE COLUMN `addstd_idx` `addstd_idx` TINYINT(3) UNSIGNED NOT NULL COMMENT '(사용안함)' AFTER `index_no`,
	CHANGE COLUMN `itemname` `itemname` VARCHAR(50) NOT NULL COMMENT '항목명' AFTER `addstd_idx`,
	CHANGE COLUMN `finame` `finame` VARCHAR(50) NOT NULL COMMENT '(사용안함)' AFTER `itemname`,
	CHANGE COLUMN `itemtype` `itemtype` VARCHAR(30) NOT NULL COMMENT '입력형식(선택형 : text 고정값)' AFTER `finame`,
	CHANGE COLUMN `bases` `bases` TEXT NOT NULL COMMENT '기초자료' AFTER `itemtype`,
	CHANGE COLUMN `custom_add` `custom_add` TEXT NOT NULL COMMENT '(사용안함)' AFTER `bases`,
	CHANGE COLUMN `sources` `sources` VARCHAR(30) NOT NULL COMMENT '(사용안함)' AFTER `custom_add`,
	CHANGE COLUMN `ishave` `ishave` CHAR(1) NOT NULL COMMENT '없음사용' AFTER `sources`,
	CHANGE COLUMN `ficou` `ficou` INT(11) NOT NULL COMMENT '(사용안함)' AFTER `ishave`;

ALTER TABLE `site_vehicle_sale`
	CHANGE COLUMN `com_idx` `com_idx` INT(10) UNSIGNED NOT NULL COMMENT 'site_rentshop.index_no' AFTER `index_no`,
	CHANGE COLUMN `name` `name` VARCHAR(200) NOT NULL COMMENT '요금정책명' AFTER `com_idx`,
	CHANGE COLUMN `acttype` `acttype` CHAR(1) NOT NULL DEFAULT '1' COMMENT '인상/할인구분(1:할인 / 2:인상)' AFTER `name`,
	CHANGE COLUMN `pertype` `pertype` CHAR(1) NOT NULL COMMENT '종류(1: 금액 / 2: %)' AFTER `acttype`,
	CHANGE COLUMN `saveper` `saveper` INT(11) NOT NULL COMMENT '할인금액 || 할인 %' AFTER `pertype`,
	CHANGE COLUMN `sdate` `sdate` DATE NOT NULL COMMENT '기간(시작)' AFTER `saveper`,
	CHANGE COLUMN `edate` `edate` DATE NOT NULL COMMENT '기간(끝)' AFTER `sdate`,
	CHANGE COLUMN `stype` `stype` CHAR(1) NOT NULL COMMENT '구분(1: 기간내전체 / 2: 특정요일)' AFTER `edate`,
	CHANGE COLUMN `chdays` `chdays` TEXT NOT NULL COMMENT 'N; / 특정요일시 요일체크 ' AFTER `stype`,
	CHANGE COLUMN `cartype` `cartype` CHAR(1) NOT NULL COMMENT '대상(1: 전체차량 / 2: 차량모델별할인 / 3: 보유차량에서선택))' AFTER `chdays`,
	CHANGE COLUMN `cars` `cars` TEXT NOT NULL COMMENT '할인차량 리스트' AFTER `cartype`,
	CHANGE COLUMN `wdate` `wdate` DATETIME NOT NULL COMMENT '등록일' AFTER `cars`;

ALTER TABLE `site_vehicle_std`
	CHANGE COLUMN `company` `company` INT(10) UNSIGNED NOT NULL COMMENT '제조사' AFTER `index_no`,
	CHANGE COLUMN `grade` `grade` INT(10) UNSIGNED NOT NULL COMMENT '차량등급(site_vehicle_attribute.ttype = 2, .index_no)' AFTER `company`,
	CHANGE COLUMN `fuel` `fuel` INT(10) UNSIGNED NOT NULL COMMENT '연료타입(site_vehicle_attribute.ttype = 3, .index_no)' AFTER `grade`,
	CHANGE COLUMN `modelname` `modelname` VARCHAR(50) NOT NULL COMMENT '모델명' AFTER `fuel`,
	CHANGE COLUMN `memcou` `memcou` TINYINT(3) UNSIGNED NOT NULL COMMENT '승차인원' AFTER `modelname`,
	CHANGE COLUMN `files` `files` VARCHAR(200) NOT NULL COMMENT '차량대표사진' AFTER `memcou`,
	CHANGE COLUMN `regidate` `regidate` DATETIME NOT NULL COMMENT '등록일' AFTER `files`,
	CHANGE COLUMN `moddate` `moddate` DATETIME NOT NULL COMMENT '수정일' AFTER `regidate`,
	CHANGE COLUMN `status` `status` CHAR(1) NOT NULL COMMENT '(사용안함)' AFTER `moddate`;