
ALTER TABLE `site_admin_grade`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_admin_priv`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_area`
	CHANGE COLUMN `index_no` `idx` INT(10) NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_bill`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_bill_ele`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_board`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_board_attach`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_board_conf`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_coupen`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_coupen_mem`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_coupen_serial`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_eng`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_est`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_faq`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_faq_attach`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_marketdb`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_marketdb_accounts`
	CHANGE COLUMN `index_no` `idx` INT(11) NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_marketdb_memo`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_marketdb_tmp`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_member`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '고유번호' FIRST;

ALTER TABLE `site_member_addinfo`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_member_card`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_member_change`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_member_grades`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_member_group`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_member_license`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_member_points`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_qna`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_rentshop`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_rentshop_loca`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_rentshop_off`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_requ`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_situation_msg`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_situation_std`
	CHANGE COLUMN `index_no` `idx` INT(11) NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_vehicle`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_vehicle_attribute`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_vehicle_off`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_vehicle_opt`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_vehicle_opt_std`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_vehicle_sale`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `site_vehicle_std`
	CHANGE COLUMN `index_no` `idx` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;